
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.ParserLexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 9;
  public static final int CHAR = 27;
  public static final int DELIMITADOR = 35;
  public static final int CHAR_T = 3;
  public static final int CASE = 52;
  public static final int DIFERENTE = 43;
  public static final int BLOQUE_C = 16;
  public static final int RESTA = 18;
  public static final int DOS_PUNTOS = 55;
  public static final int BLOQUE_A = 15;
  public static final int CORCHETE_C = 33;
  public static final int INT = 10;
  public static final int CORCHETE_A = 32;
  public static final int COMENTARIO_LINEA = 30;
  public static final int FOR = 50;
  public static final int COMENTARIO_VARIAS_LINEAS = 31;
  public static final int IGUAL = 21;
  public static final int IGUALDAD = 42;
  public static final int BOOL = 26;
  public static final int INCREMENTO = 38;
  public static final int ASIGNA = 5;
  public static final int SUMA = 17;
  public static final int IF = 47;
  public static final int MAIN = 12;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int DECREMENTO = 39;
  public static final int error = 1;
  public static final int INTEGER_T = 2;
  public static final int NEGACION = 46;
  public static final int MODULO = 36;
  public static final int MENOR = 23;
  public static final int BREAK = 54;
  public static final int ERROR = 24;
  public static final int SWITCH = 51;
  public static final int ASIGNACION = 34;
  public static final int MAYOR = 22;
  public static final int POTENCIA = 37;
  public static final int ELSE = 48;
  public static final int READ = 57;
  public static final int PARENTESIS_C = 14;
  public static final int WHILE = 49;
  public static final int PARENTESIS_A = 13;
  public static final int DEFAULT = 53;
  public static final int MAYOR_IGUAL = 41;
  public static final int FLOAT = 25;
  public static final int CONJUNCION = 44;
  public static final int STRING = 28;
  public static final int COMPARACION = 29;
  public static final int FINLINEA = 6;
  public static final int DISYUNCION = 45;
  public static final int MENOR_IGUAL = 40;
  public static final int DIVISION = 20;
  public static final int STRING_T = 4;
  public static final int PRINT = 56;
  public static final int MULTIPLICACION = 19;
  public static final int INTEGER_LITERAL = 8;
  public static final int IDENTIFIER = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER_T",
  "CHAR_T",
  "STRING_T",
  "ASIGNA",
  "FINLINEA",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "STRING_LITERAL",
  "INT",
  "RETURN",
  "MAIN",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "BLOQUE_A",
  "BLOQUE_C",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "IGUAL",
  "MAYOR",
  "MENOR",
  "ERROR",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "COMPARACION",
  "COMENTARIO_LINEA",
  "COMENTARIO_VARIAS_LINEAS",
  "CORCHETE_A",
  "CORCHETE_C",
  "ASIGNACION",
  "DELIMITADOR",
  "MODULO",
  "POTENCIA",
  "INCREMENTO",
  "DECREMENTO",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IGUALDAD",
  "DIFERENTE",
  "CONJUNCION",
  "DISYUNCION",
  "NEGACION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "DOS_PUNTOS",
  "PRINT",
  "READ"
  };
}

